In [102]:
import pandas as pd
import numpy as np
from datetime import datetime
from datetime import timedelta

In [103]:
fileName = pd.read_csv('scrubbed.csv')
df = pd.DataFrame(fileName)

In [104]:
df.head(200)

,datetime,city,state,country,shape,duration (seconds),duration (hours/min),comments,date posted,latitude,longitude
0,10/10/1949 20:30,san marcos,tx,us,cylinder,2700,45 minutes,This event took place in early fall around 194...,4/27/2004,29.8830556,-97.941111
1,10/10/1949 21:00,lackland afb,tx,NaN,light,7200,1-2 hrs,1949 Lackland AFB&#44 TX. Lights racing acros...,12/16/2005,29.38421,-98.581082
2,10/10/1955 17:00,chester (uk/england),NaN,gb,circle,20,20 seconds,Green/Orange circular disc over Chester&#44 En...,1/21/2008,53.2,-2.916667
3,10/10/1956 21:00,edna,tx,us,circle,20,1/2 hour,My older brother and twin sister were leaving ...,1/17/2004,28.9783333,-96.645833
4,10/10/1960 20:00,kaneohe,hi,us,light,900,15 minutes,AS a Marine 1st Lt. flying an FJ4B fighter/att...,1/22/2004,21.4180556,-157.803611
5,10/10/1961 19:00,bristol,tn,us,sphere,300,5 minutes,My father is now 89 my brother 52 the girl wit...,4/27/2007,36.5950000,-82.188889
6,10/10/1965 21:00,penarth (uk/wales),NaN,gb,circle,180,about 3 mins,penarth uk circle 3mins stayed 30ft above m...,2/14/2006,51.434722,-3.180000
7,10/10/1965 23:45,norwalk,ct,us,disk,1200,20 minutes,A bright orange color changing to reddish colo...,10/2/1999,41.1175000,-73.408333
8,10/10/1966 20:00,pell city,al,us,disk,180,3 minutes,Strobe Lighted disk shape object observed clos...,3/19/2009,33.5861111,-86.286111
9,10/10/1966 21:00,live oak,fl,us,disk,120,several minutes,Saucer zaps energy from powerline as my pregna...,5/11/2005,30.2947222,-82.984167
10,10/10/1968 13:00,hawthorne,ca,us,circle,300,5 min.,ROUND &#44 ORANGE &#44 WITH WHAT I WOULD SAY W...,10/31/2003,33.9163889,-118.351667
11,10/10/1968 19:00,brevard,nc,us,fireball,180,3 minutes,silent red /orange mass of energy floated by t...,6/12/2008,35.2333333,-82.734444
12,10/10/1970 16:00,bellmore,ny,us,disk,1800,30 min.,silver disc seen by family and neighbors,5/11/2000,40.6686111,-73.527500
13,10/10/1970 19:00,manchester,ky,us,unknown,180,3 minutes,Slow moving&#44 silent craft accelerated at an...,2/14/2008,37.1536111,-83.761944
14,10/10/1971 21:00,lexington,nc,us,oval,30,30 seconds,green oval shaped light over my local church&#...,2/14/2010,35.8238889,-80.253611
15,10/10/1972 19:00,harlan county,ky,us,circle,1200,20minutes,On october 10&#44 1972 myself&#44my 5yrs.daugh...,9/15/2005,36.8430556,-83.321944
16,10/10/1972 22:30,west bloomfield,mi,us,disk,120,2 minutes,The UFO was so close&#44 my battery in the car...,8/14/2007,42.5377778,-83.233056
17,10/10/1973 19:00,niantic,ct,us,disk,1800,20-30 min,Oh&#44 what a night &#33 Two (2) saucer-shape...,9/24/2003,41.3252778,-72.193611
18,10/10/1973 23:00,bermuda nas,NaN,NaN,light,20,20 sec.,saw fast moving blip on the radar scope thin w...,1/11/2002,32.364167,-64.678611
19,10/10/1974 19:30,hudson,ma,us,other,2700,45 minutes,Not sure of the eact month or year of this sig...,8/10/1999,42.3916667,-71.566667
20,10/10/1974 21:30,cardiff (uk/wales),NaN,gb,disk,1200,20 minutes,back in 1974 I was 19 at the time and lived i...,2/1/2007,51.5,-3.200000
21,10/10/1974 23:00,hudson,ks,us,light,1200,one hour?,The light chased us.,7/25/2004,38.1055556,-98.659722
22,10/10/1975 17:00,north charleston,sc,us,light,360,5-6 minutes,Several Flashing UFO lights over Charleston Na...,2/14/2008,32.8544444,-79.975000
23,10/10/1976 20:30,washougal,wa,us,oval,60,1 minute,Three extremely large lights hanging above nea...,2/7/2014,45.5827778,-122.352222
24,10/10/1976 22:00,stoke mandeville (uk/england),NaN,gb,cigar,3,3 seconds,White object over Buckinghamshire UK.,12/12/2009,51.783333,-0.783333
25,10/10/1977 12:00,san antonio,tx,us,other,30,30 seconds,i was about six or seven and my family and me ...,2/24/2005,29.4238889,-98.493333
26,10/10/1977 22:00,louisville,ky,us,light,30,approx: 30 seconds,HBCCUFO CANADIAN REPORT: Pilot Sighting Of Un...,3/17/2004,38.2541667,-85.759444
27,10/10/1978 02:00,elmont,ny,us,rectangle,300,5min,A memory I will never forget that happened men...,2/1/2007,40.7008333,-73.713333
28,10/10/1979 00:00,poughkeepsie,ny,us,chevron,900,15 minutes,1/4 moon-like&#44 its &#39chord&#39 or flat s...,4/16/2005,41.7002778,-73.921389
29,10/10/1979 22:00,saddle lake (canada),ab,NaN,triangle,270,4.5 or more min.,Lights far above&#44 that glance; then flee f...,1/19/2005,53.970571,-111.689885
...,...,...,...,...,...,...,...,...,...,...,...
170,10/10/2007 13:00,owego,ny,us,triangle,10800,3 hours,triangle with 3 llights blinking. 500 Lights O...,11/28/2007,42.1033333,-76.262500
171,10/10/2007 18:33,downingtown,pa,us,circle,120,1 to 1 1/2 minutes,Star-like (but MUCH BRIGHTER AND LARGER) light...,11/28/2007,40.0063889,-75.703611
172,10/10/2007 19:00,austin,tx,us,flash,3,3 seconds,pulsing flash recurring at 2 second intervals ...,11/28/2007,30.2669444,-97.742778
173,10/10/2007 20:10,starrsville (covington),ga,us,sphere,60,appx. 1 minute,MUFON GEORGIA FOLLOW-UP REPORT: Joint NUFORC-...,6/12/2008,33.5394444,-83.819444
174,10/10/2007 20:24,west palm beach florida,fl,NaN,fireball,180,approx 3 mins,Burning ball across the sky over central/south...,11/28/2007,26.705621,-80.036430
175,10/10/2007 20:30,conyers,ga,us,unknown,3600,1 hour,Craft seen falling and dissapears into thin ai...,11/28/2007,33.6675000,-84.017778
176,10/10/2007 20:55,vero beach,fl,us,unknown,30,30 seconds,Shooting star without red globe burn-out or de...,11/28/2007,27.6383333,-80.397500
177,10/10/2007 21:00,jensen beach,fl,us,oval,120,2 mins,A oval shaped object hovered and shot through ...,11/28/2007,27.2541667,-80.230000
178,10/10/2007 21:43,houston,tx,us,formation,35,35 seconds,Large Boomerang formation of lights over Houst...,11/28/2007,29.7630556,-95.363056
179,10/10/2007 22:00,duluth,mn,us,light,600,10 minutes,Bright pulsating light over lake superior.,1/21/2008,46.7833333,-92.106389
180,10/10/2007 22:00,fleming,co,us,circle,600,10 minutes,UFO SPOTTED&#44 FLEMING COLORADO,11/28/2007,40.6800000,-102.838889
181,10/10/2007 22:00,grove city,pa,us,unknown,3600,1:00:00,Light pattern moving silently through rapid ma...,1/21/2008,41.1577778,-80.088889
182,10/10/2007 22:00,van alstyne,tx,us,other,4,4 seconds,large mass of tiny lights all clustered togeth...,11/28/2007,33.4213889,-96.576944
183,10/10/2007 23:05,northglenn,co,us,triangle,15,15 seconds,Hovering triangular shape seen with flashing l...,11/28/2007,39.8855556,-104.986667
184,10/10/2007 23:20,stord (norway),NaN,NaN,light,600,10 min,Thise could be an ETV case&#44 but it could al...,1/21/2008,59.900209,5.282347
185,10/10/2008 02:00,london (canada),on,ca,other,120,2 min. approx,C shape with a T front over London ont on Oct ...,6/9/2009,42.983333,-81.250000
186,10/10/2008 02:00,north branch,mn,us,light,300,5 min,Lights at night&#44 shining into car and garag...,10/31/2008,45.5113889,-92.980000
187,10/10/2008 02:00,slingerlands,ny,us,circle,240,4 min,Huge&#44 moon size&#44 orange&#44 bright&#44 a...,10/31/2008,42.6291667,-73.865000
188,10/10/2008 04:00,carlin,nv,us,disk,600,10 mins,Ufo sighting in Carlin&#44 NV&#44 at the pilot...,7/19/2010,40.7138889,-116.103056
189,10/10/2008 04:50,evansville,in,us,formation,600,10 minutes+,I saw a huge V-shaped object moving slowly and...,10/31/2008,37.9747222,-87.555833
190,10/10/2008 06:00,albany,ny,us,oval,45,45 seconds,I live Colonie&#44 New York&#44 a suburb of Al...,10/31/2008,42.6525000,-73.756667
191,10/10/2008 10:22,fremont,ca,us,triangle,60,1 minute,I saw a brightly lightes v shaped ufo while dr...,10/31/2008,37.5483333,-121.987500
192,10/10/2008 18:00,yuma,az,us,triangle,900,15 minutes,Carousel in the sky on fire / pixalated triang...,10/10/2011,32.7252778,-114.623611
193,10/10/2008 19:00,south bend,in,us,light,600,10 minutes,Glowing succession of flying objects on the ho...,10/31/2008,41.6833333,-86.250000
194,10/10/2008 20:00,la crescent,mn,us,formation,10,10 seconds,six strange lights in the sky over La Crescent MN,10/31/2008,43.8280556,-91.303889
195,10/10/2008 20:00,moon township,pa,NaN,unknown,120,2 minutes,unknown rectangular shaped aircraft with brigh...,10/31/2008,40.516977,-80.221348
196,10/10/2008 20:00,philadelphia,pa,us,oval,60,1 minute,Silent&#44 oval&#44 bright white craft in yard.,7/4/2012,39.9522222,-75.164167
197,10/10/2008 20:00,seattle,wa,us,light,180,3 minutes,Around 8:00 pm? I Went out side and looked up ...,10/31/2008,47.6063889,-122.330833
198,10/10/2008 20:40,pueblo,co,us,light,300,5 minutes,In the northwest sky&#44 there were about seve...,10/31/2008,38.2544444,-104.608611
199,10/10/2008 21:30,cincinnati,oh,us,oval,900,15 minutes,12 ovel objects flying east to west orange and...,10/31/2008,39.1619444,-84.456944

In [105]:
#len(df)

In [106]:
#date_df=np.zeros(len(df.index), dtype=str)

In [107]:
#len(date_df)

In [108]:
# Code Source
# https://stackoverflow.com/questions/52688645/valueerror-time-data-10-11-2006-2400-does-not-match-format-d-m-y-hm

df['datetime_zero'] = df['datetime'].str.replace('24:00', '0:00')
df['datetime_er'] = pd.to_datetime(df['datetime_zero'], format='%m/%d/%Y %H:%M')
selrow = df['datetime'].str.contains('24:00')
df['datetime_obj'] = df['datetime_er'] + selrow * timedelta(days=1)

In [109]:
dates=[]
for index, row in df.iterrows():
    date=row['datetime_obj']
    #date_df[index] = datetime.strptime(df['datetime'][index], "%m/%d/%Y %H:%M")
    #strip_date=datetime.strptime(dates, '%m/%d/%Y %H:%M').date()
    #strip_date=dates.date()
    strip_date_object=datetime.strftime(date, '%m/%d/%Y')
    #strip_date_object.date()
    dates.append(strip_date_object)

In [101]:
#print (dates)

In [110]:
df['date']=dates

In [111]:
df.head()

,datetime,city,state,country,shape,duration (seconds),duration (hours/min),comments,date posted,latitude,longitude,datetime_zero,datetime_er,datetime_obj,date
0,10/10/1949 20:30,san marcos,tx,us,cylinder,2700,45 minutes,This event took place in early fall around 194...,4/27/2004,29.8830556,-97.941111,10/10/1949 20:30,1949-10-10 20:30:00,1949-10-10 20:30:00,10/10/1949
1,10/10/1949 21:00,lackland afb,tx,NaN,light,7200,1-2 hrs,1949 Lackland AFB&#44 TX. Lights racing acros...,12/16/2005,29.38421,-98.581082,10/10/1949 21:00,1949-10-10 21:00:00,1949-10-10 21:00:00,10/10/1949
2,10/10/1955 17:00,chester (uk/england),NaN,gb,circle,20,20 seconds,Green/Orange circular disc over Chester&#44 En...,1/21/2008,53.2,-2.916667,10/10/1955 17:00,1955-10-10 17:00:00,1955-10-10 17:00:00,10/10/1955
3,10/10/1956 21:00,edna,tx,us,circle,20,1/2 hour,My older brother and twin sister were leaving ...,1/17/2004,28.9783333,-96.645833,10/10/1956 21:00,1956-10-10 21:00:00,1956-10-10 21:00:00,10/10/1956
4,10/10/1960 20:00,kaneohe,hi,us,light,900,15 minutes,AS a Marine 1st Lt. flying an FJ4B fighter/att...,1/22/2004,21.4180556,-157.803611,10/10/1960 20:00,1960-10-10 20:00:00,1960-10-10 20:00:00,10/10/1960